version: "3"

services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    #  - ./neo4j/conf:/var/lib/neo4j/conf
      - ./neo4j/plugins:/plugins
    environment:
#- NEO4J_AUTH=neo4j/admin
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4JLABS_PLUGINS=[\"apoc\"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_AUTH=none
  keycloak:
    image: jboss/keycloak:11.0.1
    ports:
      - "8080:8080"
    environment:
      DB_VENDOR: h2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin

networks:
  internal:

volumes:
  neo4j_data:
  neo4j_logs:
